### ISSUE TITLE
Wrong configuration filename in spring.factories 

### ISSUE THREAD

**Issue by gunnarvelle** [javamelody/spring-boot-admin-server-ui-javamelody#2]
The spring.factories file specifies this config:
`org.springframework.boot.autoconfigure.EnableAutoConfiguration=spring.boot.admin.javamelody.configuration.JavamelodyAutoConfiguration` but the correct filename should be `JavaMelodyAutoConfiguration`, with a capital M.

This gives a FileNotFoundException on starting the admin-server.
```
Caused by: java.io.FileNotFoundException: class path resource [spring/boot/admin/javamelody/configuration/JavamelodyAutoConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:89)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:76)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:93)
	at org.springframework.boot.autoconfigure.AutoConfigurationSorter$AutoConfigurationClass.getAnnotationMetadata(AutoConfigurationSorter.java:213)
	... 22 common frames omitted
```

**Comment by evernat** [comment]
Thanks.
In fact, I had renamed the file but it was not causing an issue for tests in Windows.

I will release again as 1.5.7.1 now. It will be available in a few hours in Maven Central: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-boot-admin-server-ui-javamelody%22
